<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:context="http://www.springframework.org/schema/context"
        xmlns:sws="http://www.springframework.org/schema/web-services"
        xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
                            http://www.springframework.org/schema/web-services http://www.springframework.org/schema/web-services/web-services.xsd
                            http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context.xsd"
        profile="!JMSServer,QAServer">

    <!--
        SOAP Web Service configuration
    -->

    <context:component-scan base-package="com.pls.restful.shipment.webservices" />
    <sws:annotation-driven />

    <sws:dynamic-wsdl id="LtlLoadService" portTypeName="LtlLoadService" locationUri="/endpoints" targetNamespace="http://com.pls.load/">
        <sws:xsd location="classpath:/schema/LtlLoadService.xsd"/>
    </sws:dynamic-wsdl>

    <sws:interceptors>
        <bean class="com.pls.restful.shipment.webservices.endpoints.AuthenticationInterceptor"/>
    </sws:interceptors>

    <!-- UE - Unexpected Error
         SE - SQL Exception
         VE - Validation Error
         NE - Null Pointer Exception
         CV - Constraints Violation Exception
         AF - Authentication Failed
         NL - Load Not Found -->
    <bean id="ltlExceptionResolver" class="org.springframework.ws.soap.server.endpoint.SoapFaultMappingExceptionResolver">
        <property name="order" value="1"></property>
        <property name="defaultFault" value="{http://com.pls.webservices}ns:UE"/>
        <property name="warnLogCategory" value="org.springframework.ws.soap.server.endpoint.SoapFaultMappingExceptionResolver"/>
        <property name="exceptionMappings">
                <value>org.hibernate.exception.ConstraintViolationException={http://com.pls.webservices}ns:CV
                org.hibernate.exception.GenericJDBCException={http://com.pls.webservices}ns:SE
                com.pls.core.service.validation.ValidationException={http://com.pls.webservices}ns:VE
                java.lang.NullPointerException={http://com.pls.webservices}ns:NE
                com.pls.core.exception.ShipmentNotFoundException={http://com.pls.webservices}ns:NL
                org.springframework.security.core.userdetails.UsernameNotFoundException:{http://com.pls.webservices}ns:AF</value>
        </property>
    </bean>
 
</beans>